version: '2'

services:
    frontend:
        extends:
            file: docker-common.yml
            service: web
        entrypoint: /web-entrypoint.sh
        volumes:
            - ui:/home/resume/resume-frontend
    backend:
        extends:
            file: docker-common.yml
            service: django
        entrypoint: /django-entrypoint.sh
        env_file: ./docker/django/s3.env
        ports:
            - 8000:8000
        volumes:
            - api:/home/resume/resume-api
            - ui:/home/resume/resume-frontend
        links:
            - frontend
    nginx:
        extends:
            file: docker-common.yml
            service: nginx
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - api:/home/resume/resume-api
            - /var/www/logs
        links:
            - backend
volumes:
    api:
    ui:
