version: '2'

services:
    nginx:
        image: nginx
    django:
        build:
            context: ./docker/django
            dockerfile: Dockerfile
    web:
        build:
            context: ./docker/web
            dockerfile: Dockerfile
